### ISSUE TITLE
Deprecated selector in `omni-ruler/styles/omni-ruler.less`

### ISSUE THREAD

**Issue by iheart2code** [Problematic/omni-ruler#14]
In `omni-ruler/styles/omni-ruler.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .omni-ruler` => `atom-text-editor.editor .omni-ruler`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jd4no** [comment]
Any update on this?

**Comment by philoserf** [comment]
Two of us have offered a fix for the selector @Problematic . @iheart2code came first so I will bow out, closing my pull request.
