### ISSUE TITLE
HTMLElement.rootElement is deprecated. (Atom 1.1.9.0)

### ISSUE THREAD

**Issue by oriSomething** [Problematic/omni-ruler#17]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `rootElement` and access
the editor contents directly instead.
```
HTMLElement.rootElement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10)
HTMLDivElement.attachToLines (/Users/···/.atom/packages/omni-ruler/lib/omni-ruler-view.coffee:27:40)
HTMLDivElement.initialize (/Users/···/.atom/packages/omni-ruler/lib/omni-ruler-view.coffee:19:12)
<unknown> (/Users/···/.atom/packages/omni-ruler/lib/omni-ruler.coffee:28:52)
Workspace.observeTextEditors (<embedded>:26156:15)
Object.activate (/Users/···/.atom/packages/omni-ruler/lib/omni-ruler.coffee:25:29)
```

**Comment by oriSomething** [comment]
Can you please publish a new version to Atom so we can close this issue?

**Comment by cringerjs** [comment]
👍 

Fixed here but not at Atom.  So downloading in Atom will continue to show the depreciated error.

![omniruler-error](https://user-images.githubusercontent.com/835448/30194164-6226f62a-9406-11e7-88c4-20fa3e455c8f.PNG)

**Comment by Problematic** [comment]
0.6.0 has been released. Thanks, folks!
