### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by yriveiro** [Problematic/omni-ruler#4]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Function.module.exports.OmniRulerView.activate (/Users/yriveiro/.atom/packages/omni-ruler/lib/omni-ruler-view.coffee:6:11)
```

**Comment by Problematic** [comment]
Package has been updated. Thanks for the report!
