### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [Problematic/omni-ruler#8]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.3.1`) of this package:
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
2. Requiring `$` from `atom` is no longer supported. If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead: `{$} = require 'atom-space-pen-views'` or `$ = require 'jquery'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies. Or add `"jquery": "^2"` to your package dependencies.
3. Requiring `View` from `atom` is no longer supported. Please require `atom-space-pen-views` instead: `{View} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
4. Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `<pack-name>` package
5. Config::getInt is no longer necessary. Use ::get instead. Make sure the config option you are accessing has specified an `integer` schema. See the schema section of https://atom.io/docs/api/latest/Config for more info.
6. Config::getPositiveInt is no longer necessary. Use ::get instead. Make sure the config option you are accessing has specified an `integer` schema with `minimum: 1`. See the schema section of https://atom.io/docs/api/latest/Config for more info.
7. Use TextEditorView::getPaneView() instead
8. Use Workspace::onDidAddTextEditor instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by Osmose** [comment]
:+1:

@Problematic I'd be willing to help review/merge/fix stuff if you don't want to maintain this anymore. Or anything else that would help get this project active again. :D

**Comment by Problematic** [comment]
This is sort of embarrassing... I was apparently not subscribed to notifications on this repo, and had no idea that there was any activity here at all. I'll see what I can do about getting up-to-date. @Osmose any help would be more than welcome!

**Comment by Problematic** [comment]
Actually, looks like @lexicalunit is awesome and made a pull request fixing this stuff. Thank you so much.

**Comment by lexicalunit** [comment]
You're welcome! Love the package :+1:
