### ISSUE TITLE
I still only see one ruler, despite having 80 and 120 in my config.cson

### ISSUE THREAD

**Issue by calebmeyer** [Problematic/omni-ruler#9]
My config.cson: http://pastebin.com/fRG7TUGx 

Do I have it set up wrong? I'm on version 0.4.0 at the time of this posting, but I have the atom-auto-update package.

Let me know if you need more information.

**Comment by Problematic** [comment]
I just pushed up a new version (about two minutes ago) that lets you use the settings page (with comma-separated values) instead of modifying config.cson... can you update to that and let me know if you're still seeing issues?

**Comment by calebmeyer** [comment]
Tried the new version (0.4.2) with the settings page. I had to restart atom after I installed it to see the new settings, but then they worked as advertised. :beer: Cheers to you, and thanks for making awesome open source!
